const strings = {
  en: {
    appTitle: 'ScamCheck',
    analyzing: 'Analyzing...',
    analyzingSubtitle: 'Reading the message and checking links. This can take a few seconds.',
    positiveFindings: 'Positive Findings',
    noThreatsFound: 'No clear threat signals detected.',
    noPositivesFound: 'No specific reassuring signals noted.',
    recommendation: 'Recommendation',
    selectScreenshot: 'Select Screenshot',
    analyze: 'Analyze',
    analyzingPlaceholder: 'Analyzing...',
    noScreenshot: 'No screenshot selected yet.',
    allowCameraRoll: 'Please allow access to your photos so you can select a screenshot.',
    screenshotSelected: 'Screenshot selected:',
    imagesSelected: 'image(s) selected.',
    noImageFound: 'No image could be loaded from the picker result.',
    pickerError: 'Image picker error occurred.',
    settings: 'Settings',
    settingsSubtitle: 'Choose app options and language preference.',
    language: 'Language',
    selected: 'Selected',
    languageInfoTitle: 'Language info',
    languageInfoDescription: 'Switching the language will update available app labels and prompts.',
    homeSubtitle: 'Protect your inbox and brand trust by evaluating suspicious screenshots before you tap.',
    isThisMessageAScam: 'Is this message a scam?',
    uploadScreenshotAndGetCheck: 'Upload a screenshot and get an instant safety check.',
    enterSuspiciousUrl: 'Enter a suspicious URL for threat analysis.',
    selectAScreenshot: 'Select a screenshot',
    imagesReadyToAnalyze: 'Images are ready to analyze.',
    emailSmsOrAnyMessage: 'Email, SMS, or any message',
    enterUrl: 'Enter URL',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'Paste any URL you want to check for phishing or malware threats.',
    camera: 'Camera',
    gallery: 'Gallery',
    designTip: 'Design tip',
    designTipText: 'Private — nothing is stored. Always verify with the brand directly.',
    back: 'Back',
    backToResult: 'Back to Result',
    detailedThreatReport: 'Detailed Threat Report',
    screenshotAnalysis: 'Screenshot Analysis',
    urlAnalysis: 'URL Analysis',
    riskAssessment: 'Risk Assessment',
    detectedThreats: 'Detected Threats',
    systemFindings: 'System findings',
    extractedScreenshotText: 'Extracted screenshot text',
    urlInspectionDetails: 'URL inspection details',
    aiReview: 'AI review',
    systemReview: 'System review',
    urlNotRecognized: 'We could not get a clear result for this site. Our AI does not confidently recognize this domain, so it was not fully assessed. If you do not know this site, treat it with caution and verify through an official channel.',
    urlNotRecognizedStatus: 'Not assessed',
    aiThreatScore: 'Threat Score',
    recommendations: 'Recommendations',
    summary: 'Summary',
    shareReport: 'Share Report',
    shareFooter: 'Checked with ScamCheck. Always verify directly with the official source.',
    shareError: 'Could not open the share sheet.',
    hostLabel: 'Host',
    domainNotRecognizedLine: 'This domain was not confidently recognized.',
    impersonatedBrandLabel: 'Possible impersonated brand',
    noImpersonatedBrand: 'No impersonated brand detected.',
    errorNoApiKey: 'API key not found. Add EXPO_PUBLIC_FOUNDRY_API_KEY to your .env and restart the app.',
    errorApiRequest: 'The analysis service could not be reached. Please try again in a moment.',
    errorImageRead: 'Could not read the image. Please try selecting it again.',
    reviewScreenshots: 'Review screenshots',
    startNewScan: 'Start new scan',
    urlAnalysisPrefix: 'URL Analysis: ',
    deepAnalysisCompleteFor: 'Deep analysis complete for',
    securityAnalysisOf: 'Security analysis of',
    screenshotLabel: 'screenshot',
    aiThreatScanResult: 'AI Threat Scan Result',
    threatSignals: 'Threat signals',
    overallRiskScore: 'Overall Risk Score',
    analysisConfidence: 'Analysis Confidence',
    threatLevel: 'Threat Level',
    viewFullReport: 'View Full Report',
    dontClickLinks: 'Do not click on links or download files from this source.',
    reportThis: 'Report this to your email provider or IT support.',
    verifySender: 'Verify sender identity through official channels.',
    urlInspection: 'URL inspection',
    errorTitle: 'Error',
    invalidUrl: 'Please enter a valid URL',
    screenshotAnalysisDetected: 'Screenshot content was scanned and suspicious text patterns were identified in the selected images.',
    urlAnalysisComplete: 'URL analysis complete for {url}. Detailed structure checks and keyword heuristics were applied.',
    aiSummaryScreenshot: 'AI review confirms the screenshot contains text patterns consistent with phishing or credential harvesting. The system found urgent request language and account verification cues.',
    aiSummaryUrl: 'The system analyzed this URL for fake-domain (typosquatting), homograph, and suspicious-structure patterns. Review the detected signals below.',
    aiCommentHigh: 'AI suggests high threat probability and recommends immediate action.',
    aiCommentMedium: 'AI suggests medium threat probability. Proceed with caution.',
    aiCommentLow: 'AI suggests low to moderate risk but recommends verification.',
    analysisErrorTitle: 'Analysis Error',
    analysisFailed: 'Failed to analyze. Please try again.',
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    noTechnicalFlags: 'The algorithm found no obvious technical red flags.',
  },
  tr: {
    appTitle: 'ScamCheck',
    analyzing: 'Analiz ediliyor...',
    analyzingSubtitle: 'Mesaj okunuyor ve bağlantılar kontrol ediliyor. Birkaç saniye sürebilir.',
    positiveFindings: 'Olumlu Çıkarımlar',
    noThreatsFound: 'Belirgin bir tehdit işareti bulunamadı.',
    noPositivesFound: 'Özel bir güven verici işaret not edilmedi.',
    recommendation: 'Öneri',
    selectScreenshot: 'Ekran Görüntüsü Seç',
    analyze: 'Analiz Et',
    analyzingPlaceholder: 'Analiz ediliyor...',
    noScreenshot: 'Henüz ekran görüntüsü seçilmedi.',
    allowCameraRoll: 'Lütfen fotoğraflarınıza erişime izin verin.',
    screenshotSelected: 'Ekran görüntüsü seçildi:',
    imagesSelected: 'seçilen resim(ler).',
    noImageFound: 'Seçilen resim yüklenemedi.',
    pickerError: 'Resim seçici hatası oluştu.',
    settings: 'Ayarlar',
    settingsSubtitle: 'Uygulama seçeneklerini ve dil tercihlerini seçin.',
    language: 'Dil',
    selected: 'Seçili',
    languageInfoTitle: 'Dil bilgisi',
    languageInfoDescription: 'Dili değiştirmek, kullanılabilir uygulama başlıklarını ve yönergeleri güncelleyecektir.',
    homeSubtitle: 'Şüpheli ekran görüntülerini dokunmadan önce değerlendirerek gelen kutunuzu ve marka güveninizi koruyun.',
    isThisMessageAScam: 'Bu mesaj dolandırıcılık mı?',
    uploadScreenshotAndGetCheck: 'Bir ekran görüntüsü yükleyin ve anında güvenlik kontrolü alın.',
    enterSuspiciousUrl: 'Şüpheli bir URL girin.',
    selectAScreenshot: 'Ekran görüntüsü seçin',
    imagesReadyToAnalyze: 'Resimler analiz için hazır.',
    emailSmsOrAnyMessage: 'E-posta, SMS veya herhangi bir mesaj',
    enterUrl: 'URL girin',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'Kimlik avı veya kötü amaçlı yazılım tehditlerini kontrol etmek için herhangi bir URL yapıştırın.',
    camera: 'Kamera',
    gallery: 'Galeri',
    designTip: 'Tasarım ipucu',
    designTipText: 'Özel — hiçbir şey saklanmaz. Daima markayı resmi kanaldan teyit et.',
    back: 'Geri',
    backToResult: 'Sonuca Geri',
    detailedThreatReport: 'Detaylı Tehdit Raporu',
    screenshotAnalysis: 'Ekran Görüntüsü Analizi',
    urlAnalysis: 'URL Analizi',
    riskAssessment: 'Risk Değerlendirmesi',
    detectedThreats: 'Tespit Edilen Tehditler',
    systemFindings: 'Sistem bulguları',
    extractedScreenshotText: 'Çıkarılan ekran görüntüsü metni',
    urlInspectionDetails: 'URL inceleme ayrıntıları',
    aiReview: 'AI incelemesi',
    systemReview: 'Sistem incelemesi',
    urlNotRecognized: 'Bu site için net bir sonuç çıkaramadık. Yapay zekâ bu alan adını güvenle tanımıyor, bu yüzden tam olarak değerlendirilemedi. Bu siteyi tanımıyorsan temkinli yaklaş ve resmi bir kanaldan teyit et.',
    urlNotRecognizedStatus: 'Değerlendirilemedi',
    aiThreatScore: 'Tehdit Puanı',
    recommendations: 'Öneriler',
    summary: 'Özet',
    shareReport: 'Raporu Paylaş',
    shareFooter: 'ScamCheck ile kontrol edildi. Her zaman resmi kaynakla doğrudan doğrulayın.',
    shareError: 'Paylaşım penceresi açılamadı.',
    hostLabel: 'Barındırıcı',
    domainNotRecognizedLine: 'Bu alan adı güvenle tanınmadı.',
    impersonatedBrandLabel: 'Taklit edilebilecek marka',
    noImpersonatedBrand: 'Taklit edilen marka tespit edilmedi.',
    errorNoApiKey: 'API anahtarı bulunamadı. .env dosyasına EXPO_PUBLIC_FOUNDRY_API_KEY ekleyip uygulamayı yeniden başlatın.',
    errorApiRequest: 'Analiz servisine ulaşılamadı. Lütfen birazdan tekrar deneyin.',
    errorImageRead: 'Görsel okunamadı. Lütfen tekrar seçmeyi deneyin.',
    reviewScreenshots: 'Ekran görüntülerini incele',
    startNewScan: 'Yeni tarama başlat',
    urlAnalysisPrefix: 'URL Analizi: ',
    deepAnalysisCompleteFor: 'Derin analiz tamamlandı',
    securityAnalysisOf: 'Güvenlik analizi',
    screenshotLabel: 'ekran görüntüsü',
    aiThreatScanResult: 'AI Tehdit Tarama Sonucu',
    threatSignals: 'Tehdit sinyalleri',
    overallRiskScore: 'Genel Risk Puanı',
    analysisConfidence: 'Analiz Güveni',
    threatLevel: 'Tehdit Seviyesi',
    viewFullReport: 'Tam Raporu Görüntüle',
    dontClickLinks: 'Bu kaynaktan gelen bağlantılara tıklamayın veya dosya indirmeyin.',
    reportThis: 'Bunu e-posta sağlayıcınıza veya BT desteğine bildirin.',
    verifySender: 'Gönderen kimliğini resmi kanallarla doğrulayın.',
    urlInspection: 'URL incelemesi',
    errorTitle: 'Hata',
    invalidUrl: 'Lütfen geçerli bir URL girin.',
    screenshotAnalysisDetected: 'Ekran görüntüsü içeriği tarandı ve seçilen görüntülerde şüpheli metin kalıpları tespit edildi.',
    urlAnalysisComplete: '{url} için URL analizi tamamlandı. Detaylı yapı kontrolleri ve anahtar kelime kuralları uygulandı.',
    aiSummaryScreenshot: 'AI incelemesi, ekran görüntüsünün kimlik avı veya bilgi avı amaçlı metin kalıpları içerdiğini doğruluyor. Sistem acil eylem ve hesap doğrulama ifadeleri buldu.',
    aiSummaryUrl: 'Sistem bu URL’yi sahte alan adı (typosquatting), homograf ve şüpheli yapı kalıpları için analiz etti. Aşağıdaki tespit edilen işaretlere bakın.',
    aiCommentHigh: 'AI yüksek tehdit olasılığı öneriyor ve derhal işlem yapılmasını tavsiye ediyor.',
    aiCommentMedium: 'AI orta tehdit olasılığı öneriyor. Dikkatli ilerleyin.',
    aiCommentLow: 'AI düşük ila orta risk öneriyor, ancak doğrulama yapılmasını tavsiye ediyor.',
    analysisErrorTitle: 'Analiz Hatası',
    analysisFailed: 'Analiz yapılamadı. Lütfen tekrar deneyin.',
    highRisk: 'Yüksek Risk',
    mediumRisk: 'Orta Risk',
    lowRisk: 'Düşük Risk',
    noTechnicalFlags: 'Algoritma belirgin teknik tehlike işareti bulamadı.',
  },
  es: {
    appTitle: 'ScamCheck',
    analyzing: 'Analizando...',
    analyzingSubtitle: 'Leyendo el mensaje y comprobando los enlaces. Esto puede tardar unos segundos.',
    positiveFindings: 'Hallazgos positivos',
    noThreatsFound: 'No se detectaron señales claras de amenaza.',
    noPositivesFound: 'No se observaron señales tranquilizadoras específicas.',
    recommendation: 'Recomendación',
    selectScreenshot: 'Seleccionar captura',
    analyze: 'Analizar',
    analyzingPlaceholder: 'Analizando...',
    noScreenshot: 'Aún no se ha seleccionado ninguna captura.',
    allowCameraRoll: 'Permite el acceso a tus fotos para poder seleccionar una captura.',
    screenshotSelected: 'Captura seleccionada:',
    imagesSelected: 'imagen(es) seleccionada(s).',
    noImageFound: 'No se pudo cargar ninguna imagen del selector.',
    pickerError: 'Se produjo un error en el selector de imágenes.',
    settings: 'Ajustes',
    settingsSubtitle: 'Elige las opciones de la app y el idioma.',
    language: 'Idioma',
    selected: 'Seleccionado',
    languageInfoTitle: 'Información de idioma',
    languageInfoDescription: 'Cambiar el idioma actualizará las etiquetas y los textos disponibles de la app.',
    homeSubtitle: 'Protege tu bandeja de entrada y tu confianza evaluando capturas sospechosas antes de tocar.',
    isThisMessageAScam: '¿Es este mensaje una estafa?',
    uploadScreenshotAndGetCheck: 'Sube una captura y obtén una comprobación de seguridad al instante.',
    enterSuspiciousUrl: 'Introduce una URL sospechosa para analizar amenazas.',
    selectAScreenshot: 'Selecciona una captura',
    imagesReadyToAnalyze: 'Las imágenes están listas para analizar.',
    emailSmsOrAnyMessage: 'Correo, SMS o cualquier mensaje',
    enterUrl: 'Introducir URL',
    urlPlaceholder: 'https://ejemplo.com',
    pasteUrlHint: 'Pega cualquier URL que quieras comprobar por phishing o malware.',
    camera: 'Cámara',
    gallery: 'Galería',
    designTip: 'Consejo',
    designTipText: 'Privado: no se guarda nada. Verifica siempre directamente con la marca.',
    back: 'Atrás',
    backToResult: 'Volver al resultado',
    detailedThreatReport: 'Informe detallado de amenazas',
    screenshotAnalysis: 'Análisis de captura',
    urlAnalysis: 'Análisis de URL',
    riskAssessment: 'Evaluación de riesgo',
    detectedThreats: 'Amenazas detectadas',
    systemFindings: 'Hallazgos del sistema',
    extractedScreenshotText: 'Texto extraído de la captura',
    urlInspectionDetails: 'Detalles de la inspección de URL',
    aiReview: 'Revisión de IA',
    systemReview: 'Revisión del sistema',
    urlNotRecognized: 'No pudimos obtener un resultado claro para este sitio. Nuestra IA no reconoce con seguridad este dominio, por lo que no se evaluó por completo. Si no conoces este sitio, trátalo con precaución y verifícalo por un canal oficial.',
    urlNotRecognizedStatus: 'No evaluado',
    aiThreatScore: 'Puntuación de amenaza',
    recommendations: 'Recomendaciones',
    summary: 'Resumen',
    shareReport: 'Compartir informe',
    shareFooter: 'Comprobado con ScamCheck. Verifica siempre directamente con la fuente oficial.',
    shareError: 'No se pudo abrir el menú de compartir.',
    hostLabel: 'Servidor',
    domainNotRecognizedLine: 'Este dominio no se reconoció con seguridad.',
    impersonatedBrandLabel: 'Posible marca suplantada',
    noImpersonatedBrand: 'No se detectó ninguna marca suplantada.',
    errorNoApiKey: 'No se encontró la clave de API. Añade EXPO_PUBLIC_FOUNDRY_API_KEY a tu archivo .env y reinicia la app.',
    errorApiRequest: 'No se pudo conectar con el servicio de análisis. Inténtalo de nuevo en un momento.',
    errorImageRead: 'No se pudo leer la imagen. Intenta seleccionarla de nuevo.',
    reviewScreenshots: 'Revisar capturas',
    startNewScan: 'Iniciar nuevo análisis',
    urlAnalysisPrefix: 'Análisis de URL: ',
    deepAnalysisCompleteFor: 'Análisis profundo completado para',
    securityAnalysisOf: 'Análisis de seguridad de',
    screenshotLabel: 'captura',
    aiThreatScanResult: 'Resultado del análisis de amenazas con IA',
    threatSignals: 'Señales de amenaza',
    overallRiskScore: 'Puntuación de riesgo total',
    analysisConfidence: 'Confianza del análisis',
    threatLevel: 'Nivel de amenaza',
    viewFullReport: 'Ver informe completo',
    dontClickLinks: 'No hagas clic en enlaces ni descargues archivos de esta fuente.',
    reportThis: 'Informa de esto a tu proveedor de correo o soporte de TI.',
    verifySender: 'Verifica la identidad del remitente por canales oficiales.',
    urlInspection: 'Inspección de URL',
    errorTitle: 'Error',
    invalidUrl: 'Introduce una URL válida',
    screenshotAnalysisDetected: 'Se analizó el contenido de la captura y se identificaron patrones de texto sospechosos en las imágenes seleccionadas.',
    urlAnalysisComplete: 'Análisis de URL completado para {url}. Se aplicaron comprobaciones detalladas de estructura y reglas de palabras clave.',
    aiSummaryScreenshot: 'La revisión de IA confirma que la captura contiene patrones de texto propios de phishing o robo de credenciales. El sistema detectó lenguaje de urgencia y solicitudes de verificación de cuenta.',
    aiSummaryUrl: 'El sistema analizó esta URL en busca de dominios falsos (typosquatting), homógrafos y estructuras sospechosas. Revisa las señales detectadas abajo.',
    aiCommentHigh: 'La IA sugiere una alta probabilidad de amenaza y recomienda actuar de inmediato.',
    aiCommentMedium: 'La IA sugiere una probabilidad media de amenaza. Procede con precaución.',
    aiCommentLow: 'La IA sugiere un riesgo de bajo a moderado, pero recomienda verificar.',
    analysisErrorTitle: 'Error de análisis',
    analysisFailed: 'No se pudo analizar. Inténtalo de nuevo.',
    highRisk: 'Riesgo alto',
    mediumRisk: 'Riesgo medio',
    lowRisk: 'Riesgo bajo',
    noTechnicalFlags: 'El algoritmo no encontró señales técnicas evidentes de alerta.',
  },
  de: {
    appTitle: 'ScamCheck',
    analyzing: 'Wird analysiert...',
    analyzingSubtitle: 'Die Nachricht wird gelesen und Links werden geprüft. Das kann einige Sekunden dauern.',
    positiveFindings: 'Positive Befunde',
    noThreatsFound: 'Keine eindeutigen Bedrohungssignale erkannt.',
    noPositivesFound: 'Keine besonderen beruhigenden Signale festgestellt.',
    recommendation: 'Empfehlung',
    selectScreenshot: 'Screenshot auswählen',
    analyze: 'Analysieren',
    analyzingPlaceholder: 'Wird analysiert...',
    noScreenshot: 'Noch kein Screenshot ausgewählt.',
    allowCameraRoll: 'Bitte erlaube den Zugriff auf deine Fotos, um einen Screenshot auszuwählen.',
    screenshotSelected: 'Screenshot ausgewählt:',
    imagesSelected: 'Bild(er) ausgewählt.',
    noImageFound: 'Aus dem Auswahlergebnis konnte kein Bild geladen werden.',
    pickerError: 'Fehler bei der Bildauswahl aufgetreten.',
    settings: 'Einstellungen',
    settingsSubtitle: 'Wähle App-Optionen und Spracheinstellung.',
    language: 'Sprache',
    selected: 'Ausgewählt',
    languageInfoTitle: 'Sprachinfo',
    languageInfoDescription: 'Das Ändern der Sprache aktualisiert die verfügbaren App-Texte und Hinweise.',
    homeSubtitle: 'Schütze dein Postfach und dein Vertrauen, indem du verdächtige Screenshots prüfst, bevor du tippst.',
    isThisMessageAScam: 'Ist diese Nachricht Betrug?',
    uploadScreenshotAndGetCheck: 'Lade einen Screenshot hoch und erhalte sofort eine Sicherheitsprüfung.',
    enterSuspiciousUrl: 'Gib eine verdächtige URL zur Bedrohungsanalyse ein.',
    selectAScreenshot: 'Screenshot auswählen',
    imagesReadyToAnalyze: 'Die Bilder sind bereit zur Analyse.',
    emailSmsOrAnyMessage: 'E-Mail, SMS oder beliebige Nachricht',
    enterUrl: 'URL eingeben',
    urlPlaceholder: 'https://beispiel.com',
    pasteUrlHint: 'Füge eine beliebige URL ein, die du auf Phishing oder Malware prüfen möchtest.',
    camera: 'Kamera',
    gallery: 'Galerie',
    designTip: 'Tipp',
    designTipText: 'Privat – nichts wird gespeichert. Überprüfe immer direkt bei der Marke.',
    back: 'Zurück',
    backToResult: 'Zurück zum Ergebnis',
    detailedThreatReport: 'Detaillierter Bedrohungsbericht',
    screenshotAnalysis: 'Screenshot-Analyse',
    urlAnalysis: 'URL-Analyse',
    riskAssessment: 'Risikobewertung',
    detectedThreats: 'Erkannte Bedrohungen',
    systemFindings: 'Systembefunde',
    extractedScreenshotText: 'Extrahierter Screenshot-Text',
    urlInspectionDetails: 'Details der URL-Prüfung',
    aiReview: 'KI-Prüfung',
    systemReview: 'Systemprüfung',
    urlNotRecognized: 'Wir konnten für diese Seite kein eindeutiges Ergebnis erhalten. Unsere KI erkennt diese Domain nicht sicher, daher wurde sie nicht vollständig bewertet. Wenn du diese Seite nicht kennst, behandle sie mit Vorsicht und überprüfe sie über einen offiziellen Kanal.',
    urlNotRecognizedStatus: 'Nicht bewertet',
    aiThreatScore: 'Bedrohungswert',
    recommendations: 'Empfehlungen',
    summary: 'Zusammenfassung',
    shareReport: 'Bericht teilen',
    shareFooter: 'Mit ScamCheck geprüft. Überprüfe immer direkt bei der offiziellen Quelle.',
    shareError: 'Das Teilen-Menü konnte nicht geöffnet werden.',
    hostLabel: 'Host',
    domainNotRecognizedLine: 'Diese Domain wurde nicht sicher erkannt.',
    impersonatedBrandLabel: 'Mögliche nachgeahmte Marke',
    noImpersonatedBrand: 'Keine nachgeahmte Marke erkannt.',
    errorNoApiKey: 'API-Schlüssel nicht gefunden. Füge EXPO_PUBLIC_FOUNDRY_API_KEY zu deiner .env-Datei hinzu und starte die App neu.',
    errorApiRequest: 'Der Analysedienst war nicht erreichbar. Bitte versuche es gleich noch einmal.',
    errorImageRead: 'Das Bild konnte nicht gelesen werden. Bitte wähle es erneut aus.',
    reviewScreenshots: 'Screenshots prüfen',
    startNewScan: 'Neuen Scan starten',
    urlAnalysisPrefix: 'URL-Analyse: ',
    deepAnalysisCompleteFor: 'Tiefenanalyse abgeschlossen für',
    securityAnalysisOf: 'Sicherheitsanalyse von',
    screenshotLabel: 'Screenshot',
    aiThreatScanResult: 'KI-Bedrohungsscan-Ergebnis',
    threatSignals: 'Bedrohungssignale',
    overallRiskScore: 'Gesamtrisikowert',
    analysisConfidence: 'Analysesicherheit',
    threatLevel: 'Bedrohungsstufe',
    viewFullReport: 'Vollständigen Bericht ansehen',
    dontClickLinks: 'Klicke nicht auf Links und lade keine Dateien aus dieser Quelle herunter.',
    reportThis: 'Melde dies deinem E-Mail-Anbieter oder IT-Support.',
    verifySender: 'Überprüfe die Identität des Absenders über offizielle Kanäle.',
    urlInspection: 'URL-Prüfung',
    errorTitle: 'Fehler',
    invalidUrl: 'Bitte gib eine gültige URL ein',
    screenshotAnalysisDetected: 'Der Screenshot-Inhalt wurde gescannt und in den ausgewählten Bildern wurden verdächtige Textmuster erkannt.',
    urlAnalysisComplete: 'URL-Analyse abgeschlossen für {url}. Detaillierte Strukturprüfungen und Schlüsselwortregeln wurden angewendet.',
    aiSummaryScreenshot: 'Die KI-Prüfung bestätigt, dass der Screenshot Textmuster enthält, die zu Phishing oder Datendiebstahl passen. Das System fand dringliche Formulierungen und Aufforderungen zur Kontobestätigung.',
    aiSummaryUrl: 'Das System hat diese URL auf gefälschte Domains (Typosquatting), Homografen und verdächtige Strukturen geprüft. Sieh dir die erkannten Signale unten an.',
    aiCommentHigh: 'Die KI vermutet eine hohe Bedrohungswahrscheinlichkeit und empfiehlt sofortiges Handeln.',
    aiCommentMedium: 'Die KI vermutet eine mittlere Bedrohungswahrscheinlichkeit. Gehe vorsichtig vor.',
    aiCommentLow: 'Die KI vermutet ein geringes bis mittleres Risiko, empfiehlt aber eine Überprüfung.',
    analysisErrorTitle: 'Analysefehler',
    analysisFailed: 'Analyse fehlgeschlagen. Bitte versuche es erneut.',
    highRisk: 'Hohes Risiko',
    mediumRisk: 'Mittleres Risiko',
    lowRisk: 'Geringes Risiko',
    noTechnicalFlags: 'Der Algorithmus fand keine offensichtlichen technischen Warnzeichen.',
  },
  fr: {
    appTitle: 'ScamCheck',
    analyzing: 'Analyse en cours...',
    analyzingSubtitle: 'Lecture du message et vérification des liens. Cela peut prendre quelques secondes.',
    positiveFindings: 'Constats positifs',
    noThreatsFound: 'Aucun signe clair de menace détecté.',
    noPositivesFound: 'Aucun signe rassurant particulier relevé.',
    recommendation: 'Recommandation',
    selectScreenshot: 'Choisir une capture',
    analyze: 'Analyser',
    analyzingPlaceholder: 'Analyse en cours...',
    noScreenshot: 'Aucune capture sélectionnée pour le moment.',
    allowCameraRoll: 'Autorise l’accès à tes photos pour pouvoir choisir une capture.',
    screenshotSelected: 'Capture sélectionnée :',
    imagesSelected: 'image(s) sélectionnée(s).',
    noImageFound: 'Aucune image n’a pu être chargée depuis le sélecteur.',
    pickerError: 'Une erreur du sélecteur d’images s’est produite.',
    settings: 'Paramètres',
    settingsSubtitle: 'Choisis les options de l’app et la langue.',
    language: 'Langue',
    selected: 'Sélectionné',
    languageInfoTitle: 'Infos sur la langue',
    languageInfoDescription: 'Changer la langue mettra à jour les libellés et messages disponibles de l’app.',
    homeSubtitle: 'Protège ta boîte de réception et ta confiance en évaluant les captures suspectes avant de cliquer.',
    isThisMessageAScam: 'Ce message est-il une arnaque ?',
    uploadScreenshotAndGetCheck: 'Envoie une capture et obtiens une vérification de sécurité instantanée.',
    enterSuspiciousUrl: 'Saisis une URL suspecte pour analyser les menaces.',
    selectAScreenshot: 'Choisis une capture',
    imagesReadyToAnalyze: 'Les images sont prêtes à être analysées.',
    emailSmsOrAnyMessage: 'E-mail, SMS ou tout message',
    enterUrl: 'Saisir une URL',
    urlPlaceholder: 'https://exemple.com',
    pasteUrlHint: 'Colle n’importe quelle URL à vérifier pour le phishing ou les malwares.',
    camera: 'Appareil photo',
    gallery: 'Galerie',
    designTip: 'Astuce',
    designTipText: 'Privé – rien n’est stocké. Vérifie toujours directement auprès de la marque.',
    back: 'Retour',
    backToResult: 'Retour au résultat',
    detailedThreatReport: 'Rapport détaillé des menaces',
    screenshotAnalysis: 'Analyse de capture',
    urlAnalysis: 'Analyse d’URL',
    riskAssessment: 'Évaluation du risque',
    detectedThreats: 'Menaces détectées',
    systemFindings: 'Constats du système',
    extractedScreenshotText: 'Texte extrait de la capture',
    urlInspectionDetails: 'Détails de l’inspection d’URL',
    aiReview: 'Analyse IA',
    systemReview: 'Analyse du système',
    urlNotRecognized: 'Nous n’avons pas pu obtenir de résultat clair pour ce site. Notre IA ne reconnaît pas ce domaine avec certitude, il n’a donc pas été entièrement évalué. Si tu ne connais pas ce site, traite-le avec prudence et vérifie-le via un canal officiel.',
    urlNotRecognizedStatus: 'Non évalué',
    aiThreatScore: 'Score de menace',
    recommendations: 'Recommandations',
    summary: 'Résumé',
    shareReport: 'Partager le rapport',
    shareFooter: 'Vérifié avec ScamCheck. Vérifie toujours directement auprès de la source officielle.',
    shareError: 'Impossible d’ouvrir le menu de partage.',
    hostLabel: 'Hôte',
    domainNotRecognizedLine: 'Ce domaine n’a pas été reconnu avec certitude.',
    impersonatedBrandLabel: 'Marque potentiellement usurpée',
    noImpersonatedBrand: 'Aucune marque usurpée détectée.',
    errorNoApiKey: 'Clé API introuvable. Ajoute EXPO_PUBLIC_FOUNDRY_API_KEY à ton fichier .env et redémarre l’app.',
    errorApiRequest: 'Le service d’analyse est injoignable. Réessaie dans un instant.',
    errorImageRead: 'Impossible de lire l’image. Essaie de la sélectionner à nouveau.',
    reviewScreenshots: 'Revoir les captures',
    startNewScan: 'Nouvelle analyse',
    urlAnalysisPrefix: 'Analyse d’URL : ',
    deepAnalysisCompleteFor: 'Analyse approfondie terminée pour',
    securityAnalysisOf: 'Analyse de sécurité de',
    screenshotLabel: 'capture',
    aiThreatScanResult: 'Résultat de l’analyse des menaces par IA',
    threatSignals: 'Signaux de menace',
    overallRiskScore: 'Score de risque global',
    analysisConfidence: 'Confiance de l’analyse',
    threatLevel: 'Niveau de menace',
    viewFullReport: 'Voir le rapport complet',
    dontClickLinks: 'Ne clique pas sur les liens et ne télécharge aucun fichier de cette source.',
    reportThis: 'Signale ceci à ton fournisseur de messagerie ou au support informatique.',
    verifySender: 'Vérifie l’identité de l’expéditeur via des canaux officiels.',
    urlInspection: 'Inspection d’URL',
    errorTitle: 'Erreur',
    invalidUrl: 'Saisis une URL valide',
    screenshotAnalysisDetected: 'Le contenu de la capture a été analysé et des schémas de texte suspects ont été identifiés dans les images sélectionnées.',
    urlAnalysisComplete: 'Analyse d’URL terminée pour {url}. Des vérifications détaillées de structure et des règles de mots-clés ont été appliquées.',
    aiSummaryScreenshot: 'L’analyse IA confirme que la capture contient des schémas de texte typiques du phishing ou du vol d’identifiants. Le système a détecté un langage d’urgence et des demandes de vérification de compte.',
    aiSummaryUrl: 'Le système a analysé cette URL à la recherche de faux domaines (typosquatting), d’homographes et de structures suspectes. Consulte les signaux détectés ci-dessous.',
    aiCommentHigh: 'L’IA suggère une forte probabilité de menace et recommande d’agir immédiatement.',
    aiCommentMedium: 'L’IA suggère une probabilité de menace moyenne. Procède avec prudence.',
    aiCommentLow: 'L’IA suggère un risque faible à modéré mais recommande une vérification.',
    analysisErrorTitle: 'Erreur d’analyse',
    analysisFailed: 'Échec de l’analyse. Réessaie.',
    highRisk: 'Risque élevé',
    mediumRisk: 'Risque moyen',
    lowRisk: 'Risque faible',
    noTechnicalFlags: 'L’algorithme n’a trouvé aucun signal technique d’alerte évident.',
  },
  ar: {
    appTitle: 'ScamCheck',
    analyzing: 'جارٍ التحليل...',
    analyzingSubtitle: 'تتم قراءة الرسالة والتحقق من الروابط. قد يستغرق ذلك بضع ثوانٍ.',
    positiveFindings: 'نتائج إيجابية',
    noThreatsFound: 'لم يتم اكتشاف إشارات تهديد واضحة.',
    noPositivesFound: 'لم تُلاحَظ إشارات مطمئنة محددة.',
    recommendation: 'توصية',
    selectScreenshot: 'اختيار لقطة شاشة',
    analyze: 'تحليل',
    analyzingPlaceholder: 'جارٍ التحليل...',
    noScreenshot: 'لم يتم اختيار لقطة شاشة بعد.',
    allowCameraRoll: 'يرجى السماح بالوصول إلى صورك لاختيار لقطة شاشة.',
    screenshotSelected: 'تم اختيار لقطة الشاشة:',
    imagesSelected: 'صورة (صور) مختارة.',
    noImageFound: 'تعذّر تحميل أي صورة من المُحدِّد.',
    pickerError: 'حدث خطأ في مُحدِّد الصور.',
    settings: 'الإعدادات',
    settingsSubtitle: 'اختر خيارات التطبيق واللغة.',
    language: 'اللغة',
    selected: 'محدد',
    languageInfoTitle: 'معلومات اللغة',
    languageInfoDescription: 'سيؤدي تغيير اللغة إلى تحديث نصوص التطبيق ورسائله المتاحة.',
    homeSubtitle: 'احمِ بريدك وثقتك من خلال تقييم لقطات الشاشة المشبوهة قبل النقر.',
    isThisMessageAScam: 'هل هذه الرسالة احتيال؟',
    uploadScreenshotAndGetCheck: 'ارفع لقطة شاشة واحصل على فحص أمان فوري.',
    enterSuspiciousUrl: 'أدخل رابطًا مشبوهًا لتحليل التهديدات.',
    selectAScreenshot: 'اختر لقطة شاشة',
    imagesReadyToAnalyze: 'الصور جاهزة للتحليل.',
    emailSmsOrAnyMessage: 'بريد إلكتروني أو رسالة نصية أو أي رسالة',
    enterUrl: 'أدخل الرابط',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'الصق أي رابط تريد فحصه بحثًا عن التصيّد أو البرامج الضارة.',
    camera: 'الكاميرا',
    gallery: 'المعرض',
    designTip: 'نصيحة',
    designTipText: 'خاص — لا يتم تخزين أي شيء. تحقق دائمًا مباشرةً من العلامة التجارية.',
    back: 'رجوع',
    backToResult: 'العودة إلى النتيجة',
    detailedThreatReport: 'تقرير مفصّل عن التهديدات',
    screenshotAnalysis: 'تحليل لقطة الشاشة',
    urlAnalysis: 'تحليل الرابط',
    riskAssessment: 'تقييم المخاطر',
    detectedThreats: 'التهديدات المكتشفة',
    systemFindings: 'نتائج النظام',
    extractedScreenshotText: 'النص المستخرج من لقطة الشاشة',
    urlInspectionDetails: 'تفاصيل فحص الرابط',
    aiReview: 'مراجعة الذكاء الاصطناعي',
    systemReview: 'مراجعة النظام',
    urlNotRecognized: 'تعذّر الحصول على نتيجة واضحة لهذا الموقع. لا يتعرّف الذكاء الاصطناعي لدينا على هذا النطاق بثقة، لذا لم يتم تقييمه بالكامل. إذا كنت لا تعرف هذا الموقع، فتعامل معه بحذر وتحقق منه عبر قناة رسمية.',
    urlNotRecognizedStatus: 'لم يُقيَّم',
    aiThreatScore: 'درجة التهديد',
    recommendations: 'التوصيات',
    summary: 'ملخص',
    shareReport: 'مشاركة التقرير',
    shareFooter: 'تم الفحص باستخدام ScamCheck. تحقق دائمًا مباشرةً من المصدر الرسمي.',
    shareError: 'تعذّر فتح قائمة المشاركة.',
    hostLabel: 'المضيف',
    domainNotRecognizedLine: 'لم يتم التعرف على هذا النطاق بثقة.',
    impersonatedBrandLabel: 'علامة تجارية يُحتمل انتحالها',
    noImpersonatedBrand: 'لم يتم اكتشاف علامة تجارية منتحَلة.',
    errorNoApiKey: 'لم يتم العثور على مفتاح API. أضف EXPO_PUBLIC_FOUNDRY_API_KEY إلى ملف .env وأعد تشغيل التطبيق.',
    errorApiRequest: 'تعذّر الوصول إلى خدمة التحليل. حاول مرة أخرى بعد لحظة.',
    errorImageRead: 'تعذّر قراءة الصورة. حاول اختيارها مرة أخرى.',
    reviewScreenshots: 'مراجعة لقطات الشاشة',
    startNewScan: 'بدء فحص جديد',
    urlAnalysisPrefix: 'تحليل الرابط: ',
    deepAnalysisCompleteFor: 'اكتمل التحليل المعمّق لـ',
    securityAnalysisOf: 'تحليل أمان لـ',
    screenshotLabel: 'لقطة شاشة',
    aiThreatScanResult: 'نتيجة فحص التهديدات بالذكاء الاصطناعي',
    threatSignals: 'إشارات التهديد',
    overallRiskScore: 'درجة المخاطر الإجمالية',
    analysisConfidence: 'موثوقية التحليل',
    threatLevel: 'مستوى التهديد',
    viewFullReport: 'عرض التقرير الكامل',
    dontClickLinks: 'لا تنقر على الروابط أو تنزّل ملفات من هذا المصدر.',
    reportThis: 'أبلغ عن ذلك لمزوّد بريدك الإلكتروني أو دعم تقنية المعلومات.',
    verifySender: 'تحقق من هوية المرسِل عبر القنوات الرسمية.',
    urlInspection: 'فحص الرابط',
    errorTitle: 'خطأ',
    invalidUrl: 'يرجى إدخال رابط صالح',
    screenshotAnalysisDetected: 'تم فحص محتوى لقطة الشاشة وتم تحديد أنماط نصية مشبوهة في الصور المختارة.',
    urlAnalysisComplete: 'اكتمل تحليل الرابط لـ {url}. تم تطبيق فحوصات بنية مفصّلة وقواعد كلمات مفتاحية.',
    aiSummaryScreenshot: 'تؤكد مراجعة الذكاء الاصطناعي أن لقطة الشاشة تحتوي على أنماط نصية تتوافق مع التصيّد أو سرقة بيانات الاعتماد. اكتشف النظام لغة إلحاح وطلبات للتحقق من الحساب.',
    aiSummaryUrl: 'حلّل النظام هذا الرابط بحثًا عن نطاقات مزيفة (تزييف الأخطاء المطبعية) والمتشابهات والبنية المشبوهة. راجع الإشارات المكتشفة أدناه.',
    aiCommentHigh: 'يشير الذكاء الاصطناعي إلى احتمال تهديد مرتفع ويوصي باتخاذ إجراء فوري.',
    aiCommentMedium: 'يشير الذكاء الاصطناعي إلى احتمال تهديد متوسط. تابع بحذر.',
    aiCommentLow: 'يشير الذكاء الاصطناعي إلى خطر منخفض إلى متوسط لكنه يوصي بالتحقق.',
    analysisErrorTitle: 'خطأ في التحليل',
    analysisFailed: 'فشل التحليل. حاول مرة أخرى.',
    highRisk: 'خطر مرتفع',
    mediumRisk: 'خطر متوسط',
    lowRisk: 'خطر منخفض',
    noTechnicalFlags: 'لم يجد الخوارزم أي إشارات تقنية تحذيرية واضحة.',
  },
  pt: {
    appTitle: 'ScamCheck',
    analyzing: 'A analisar...',
    analyzingSubtitle: 'A ler a mensagem e a verificar os links. Isto pode demorar alguns segundos.',
    positiveFindings: 'Constatações positivas',
    noThreatsFound: 'Nenhum sinal claro de ameaça detetado.',
    noPositivesFound: 'Nenhum sinal tranquilizador específico observado.',
    recommendation: 'Recomendação',
    selectScreenshot: 'Selecionar captura',
    analyze: 'Analisar',
    analyzingPlaceholder: 'A analisar...',
    noScreenshot: 'Ainda não foi selecionada nenhuma captura.',
    allowCameraRoll: 'Permite o acesso às tuas fotos para poderes selecionar uma captura.',
    screenshotSelected: 'Captura selecionada:',
    imagesSelected: 'imagem(ns) selecionada(s).',
    noImageFound: 'Não foi possível carregar nenhuma imagem do seletor.',
    pickerError: 'Ocorreu um erro no seletor de imagens.',
    settings: 'Definições',
    settingsSubtitle: 'Escolhe as opções da app e o idioma.',
    language: 'Idioma',
    selected: 'Selecionado',
    languageInfoTitle: 'Informação de idioma',
    languageInfoDescription: 'Mudar o idioma irá atualizar os textos e mensagens disponíveis da app.',
    homeSubtitle: 'Protege a tua caixa de entrada e a tua confiança avaliando capturas suspeitas antes de tocar.',
    isThisMessageAScam: 'Esta mensagem é uma fraude?',
    uploadScreenshotAndGetCheck: 'Carrega uma captura e obtém uma verificação de segurança instantânea.',
    enterSuspiciousUrl: 'Introduz um URL suspeito para analisar ameaças.',
    selectAScreenshot: 'Seleciona uma captura',
    imagesReadyToAnalyze: 'As imagens estão prontas para analisar.',
    emailSmsOrAnyMessage: 'E-mail, SMS ou qualquer mensagem',
    enterUrl: 'Introduzir URL',
    urlPlaceholder: 'https://exemplo.com',
    pasteUrlHint: 'Cola qualquer URL que queiras verificar quanto a phishing ou malware.',
    camera: 'Câmara',
    gallery: 'Galeria',
    designTip: 'Dica',
    designTipText: 'Privado – nada é guardado. Verifica sempre diretamente com a marca.',
    back: 'Voltar',
    backToResult: 'Voltar ao resultado',
    detailedThreatReport: 'Relatório detalhado de ameaças',
    screenshotAnalysis: 'Análise de captura',
    urlAnalysis: 'Análise de URL',
    riskAssessment: 'Avaliação de risco',
    detectedThreats: 'Ameaças detetadas',
    systemFindings: 'Constatações do sistema',
    extractedScreenshotText: 'Texto extraído da captura',
    urlInspectionDetails: 'Detalhes da inspeção de URL',
    aiReview: 'Análise de IA',
    systemReview: 'Análise do sistema',
    urlNotRecognized: 'Não foi possível obter um resultado claro para este site. A nossa IA não reconhece este domínio com confiança, por isso não foi totalmente avaliado. Se não conheces este site, trata-o com cuidado e verifica-o através de um canal oficial.',
    urlNotRecognizedStatus: 'Não avaliado',
    aiThreatScore: 'Pontuação de ameaça',
    recommendations: 'Recomendações',
    summary: 'Resumo',
    shareReport: 'Partilhar relatório',
    shareFooter: 'Verificado com ScamCheck. Verifica sempre diretamente com a fonte oficial.',
    shareError: 'Não foi possível abrir o menu de partilha.',
    hostLabel: 'Servidor',
    domainNotRecognizedLine: 'Este domínio não foi reconhecido com confiança.',
    impersonatedBrandLabel: 'Possível marca falsificada',
    noImpersonatedBrand: 'Nenhuma marca falsificada detetada.',
    errorNoApiKey: 'Chave de API não encontrada. Adiciona EXPO_PUBLIC_FOUNDRY_API_KEY ao teu ficheiro .env e reinicia a app.',
    errorApiRequest: 'Não foi possível contactar o serviço de análise. Tenta novamente daqui a pouco.',
    errorImageRead: 'Não foi possível ler a imagem. Tenta selecioná-la novamente.',
    reviewScreenshots: 'Rever capturas',
    startNewScan: 'Iniciar nova análise',
    urlAnalysisPrefix: 'Análise de URL: ',
    deepAnalysisCompleteFor: 'Análise aprofundada concluída para',
    securityAnalysisOf: 'Análise de segurança de',
    screenshotLabel: 'captura',
    aiThreatScanResult: 'Resultado da análise de ameaças por IA',
    threatSignals: 'Sinais de ameaça',
    overallRiskScore: 'Pontuação de risco total',
    analysisConfidence: 'Confiança da análise',
    threatLevel: 'Nível de ameaça',
    viewFullReport: 'Ver relatório completo',
    dontClickLinks: 'Não cliques em links nem descarregues ficheiros desta fonte.',
    reportThis: 'Comunica isto ao teu fornecedor de e-mail ou suporte de TI.',
    verifySender: 'Verifica a identidade do remetente através de canais oficiais.',
    urlInspection: 'Inspeção de URL',
    errorTitle: 'Erro',
    invalidUrl: 'Introduz um URL válido',
    screenshotAnalysisDetected: 'O conteúdo da captura foi analisado e foram identificados padrões de texto suspeitos nas imagens selecionadas.',
    urlAnalysisComplete: 'Análise de URL concluída para {url}. Foram aplicadas verificações detalhadas de estrutura e regras de palavras-chave.',
    aiSummaryScreenshot: 'A análise de IA confirma que a captura contém padrões de texto típicos de phishing ou roubo de credenciais. O sistema detetou linguagem de urgência e pedidos de verificação de conta.',
    aiSummaryUrl: 'O sistema analisou este URL em busca de domínios falsos (typosquatting), homógrafos e estruturas suspeitas. Vê os sinais detetados abaixo.',
    aiCommentHigh: 'A IA sugere uma alta probabilidade de ameaça e recomenda ação imediata.',
    aiCommentMedium: 'A IA sugere uma probabilidade média de ameaça. Procede com cuidado.',
    aiCommentLow: 'A IA sugere um risco baixo a moderado, mas recomenda verificação.',
    analysisErrorTitle: 'Erro de análise',
    analysisFailed: 'Falha ao analisar. Tenta novamente.',
    highRisk: 'Risco alto',
    mediumRisk: 'Risco médio',
    lowRisk: 'Risco baixo',
    noTechnicalFlags: 'O algoritmo não encontrou sinais técnicos óbvios de alerta.',
  },
  ru: {
    appTitle: 'ScamCheck',
    analyzing: 'Анализ...',
    analyzingSubtitle: 'Чтение сообщения и проверка ссылок. Это может занять несколько секунд.',
    positiveFindings: 'Положительные результаты',
    noThreatsFound: 'Явных признаков угрозы не обнаружено.',
    noPositivesFound: 'Особых обнадёживающих сигналов не отмечено.',
    recommendation: 'Рекомендация',
    selectScreenshot: 'Выбрать скриншот',
    analyze: 'Анализировать',
    analyzingPlaceholder: 'Анализ...',
    noScreenshot: 'Скриншот ещё не выбран.',
    allowCameraRoll: 'Разрешите доступ к фото, чтобы выбрать скриншот.',
    screenshotSelected: 'Скриншот выбран:',
    imagesSelected: 'изображение(я) выбрано.',
    noImageFound: 'Не удалось загрузить изображение из выбора.',
    pickerError: 'Произошла ошибка выбора изображения.',
    settings: 'Настройки',
    settingsSubtitle: 'Выберите параметры приложения и язык.',
    language: 'Язык',
    selected: 'Выбрано',
    languageInfoTitle: 'О языке',
    languageInfoDescription: 'Смена языка обновит доступные надписи и сообщения приложения.',
    homeSubtitle: 'Защитите свою почту и доверие, проверяя подозрительные скриншоты перед нажатием.',
    isThisMessageAScam: 'Это сообщение — мошенничество?',
    uploadScreenshotAndGetCheck: 'Загрузите скриншот и получите мгновенную проверку безопасности.',
    enterSuspiciousUrl: 'Введите подозрительный URL для анализа угроз.',
    selectAScreenshot: 'Выберите скриншот',
    imagesReadyToAnalyze: 'Изображения готовы к анализу.',
    emailSmsOrAnyMessage: 'Эл. почта, SMS или любое сообщение',
    enterUrl: 'Введите URL',
    urlPlaceholder: 'https://primer.com',
    pasteUrlHint: 'Вставьте любой URL для проверки на фишинг или вредоносное ПО.',
    camera: 'Камера',
    gallery: 'Галерея',
    designTip: 'Совет',
    designTipText: 'Конфиденциально — ничего не сохраняется. Всегда проверяйте напрямую у бренда.',
    back: 'Назад',
    backToResult: 'Назад к результату',
    detailedThreatReport: 'Подробный отчёт об угрозах',
    screenshotAnalysis: 'Анализ скриншота',
    urlAnalysis: 'Анализ URL',
    riskAssessment: 'Оценка риска',
    detectedThreats: 'Обнаруженные угрозы',
    systemFindings: 'Результаты системы',
    extractedScreenshotText: 'Извлечённый текст со скриншота',
    urlInspectionDetails: 'Детали проверки URL',
    aiReview: 'Анализ ИИ',
    systemReview: 'Анализ системы',
    urlNotRecognized: 'Не удалось получить чёткий результат для этого сайта. Наш ИИ не распознаёт этот домен с уверенностью, поэтому он не был полностью оценён. Если вы не знаете этот сайт, отнеситесь к нему с осторожностью и проверьте через официальный канал.',
    urlNotRecognizedStatus: 'Не оценено',
    aiThreatScore: 'Оценка угрозы',
    recommendations: 'Рекомендации',
    summary: 'Сводка',
    shareReport: 'Поделиться отчётом',
    shareFooter: 'Проверено с ScamCheck. Всегда проверяйте напрямую у официального источника.',
    shareError: 'Не удалось открыть меню «Поделиться».',
    hostLabel: 'Хост',
    domainNotRecognizedLine: 'Этот домен не был распознан с уверенностью.',
    impersonatedBrandLabel: 'Возможно поддельный бренд',
    noImpersonatedBrand: 'Поддельный бренд не обнаружен.',
    errorNoApiKey: 'Ключ API не найден. Добавьте EXPO_PUBLIC_FOUNDRY_API_KEY в файл .env и перезапустите приложение.',
    errorApiRequest: 'Не удалось связаться со службой анализа. Повторите попытку через мгновение.',
    errorImageRead: 'Не удалось прочитать изображение. Попробуйте выбрать его снова.',
    reviewScreenshots: 'Просмотреть скриншоты',
    startNewScan: 'Начать новую проверку',
    urlAnalysisPrefix: 'Анализ URL: ',
    deepAnalysisCompleteFor: 'Глубокий анализ завершён для',
    securityAnalysisOf: 'Анализ безопасности для',
    screenshotLabel: 'скриншот',
    aiThreatScanResult: 'Результат сканирования угроз ИИ',
    threatSignals: 'Сигналы угрозы',
    overallRiskScore: 'Общая оценка риска',
    analysisConfidence: 'Достоверность анализа',
    threatLevel: 'Уровень угрозы',
    viewFullReport: 'Показать полный отчёт',
    dontClickLinks: 'Не нажимайте на ссылки и не скачивайте файлы из этого источника.',
    reportThis: 'Сообщите об этом своему почтовому провайдеру или в ИТ-поддержку.',
    verifySender: 'Проверьте личность отправителя через официальные каналы.',
    urlInspection: 'Проверка URL',
    errorTitle: 'Ошибка',
    invalidUrl: 'Введите корректный URL',
    screenshotAnalysisDetected: 'Содержимое скриншота было просканировано, и в выбранных изображениях обнаружены подозрительные текстовые шаблоны.',
    urlAnalysisComplete: 'Анализ URL завершён для {url}. Применены подробные проверки структуры и правила ключевых слов.',
    aiSummaryScreenshot: 'Анализ ИИ подтверждает, что скриншот содержит текстовые шаблоны, характерные для фишинга или кражи учётных данных. Система обнаружила язык срочности и запросы подтверждения аккаунта.',
    aiSummaryUrl: 'Система проанализировала этот URL на поддельные домены (тайпсквоттинг), омографы и подозрительную структуру. Просмотрите обнаруженные сигналы ниже.',
    aiCommentHigh: 'ИИ предполагает высокую вероятность угрозы и рекомендует немедленные действия.',
    aiCommentMedium: 'ИИ предполагает среднюю вероятность угрозы. Действуйте осторожно.',
    aiCommentLow: 'ИИ предполагает низкий или умеренный риск, но рекомендует проверку.',
    analysisErrorTitle: 'Ошибка анализа',
    analysisFailed: 'Не удалось проанализировать. Повторите попытку.',
    highRisk: 'Высокий риск',
    mediumRisk: 'Средний риск',
    lowRisk: 'Низкий риск',
    noTechnicalFlags: 'Алгоритм не обнаружил явных технических признаков угрозы.',
  },
  it: {
    appTitle: 'ScamCheck',
    analyzing: 'Analisi in corso...',
    analyzingSubtitle: 'Lettura del messaggio e controllo dei link. Può richiedere alcuni secondi.',
    positiveFindings: 'Riscontri positivi',
    noThreatsFound: 'Nessun segnale di minaccia evidente rilevato.',
    noPositivesFound: 'Nessun segnale rassicurante particolare rilevato.',
    recommendation: 'Raccomandazione',
    selectScreenshot: 'Seleziona screenshot',
    analyze: 'Analizza',
    analyzingPlaceholder: 'Analisi in corso...',
    noScreenshot: 'Nessuno screenshot ancora selezionato.',
    allowCameraRoll: 'Consenti l’accesso alle tue foto per poter selezionare uno screenshot.',
    screenshotSelected: 'Screenshot selezionato:',
    imagesSelected: 'immagine/i selezionata/e.',
    noImageFound: 'Impossibile caricare un’immagine dal selettore.',
    pickerError: 'Si è verificato un errore del selettore di immagini.',
    settings: 'Impostazioni',
    settingsSubtitle: 'Scegli le opzioni dell’app e la lingua.',
    language: 'Lingua',
    selected: 'Selezionato',
    languageInfoTitle: 'Info lingua',
    languageInfoDescription: 'Cambiare lingua aggiornerà le etichette e i messaggi disponibili dell’app.',
    homeSubtitle: 'Proteggi la tua casella e la tua fiducia valutando gli screenshot sospetti prima di toccare.',
    isThisMessageAScam: 'Questo messaggio è una truffa?',
    uploadScreenshotAndGetCheck: 'Carica uno screenshot e ottieni un controllo di sicurezza immediato.',
    enterSuspiciousUrl: 'Inserisci un URL sospetto per l’analisi delle minacce.',
    selectAScreenshot: 'Seleziona uno screenshot',
    imagesReadyToAnalyze: 'Le immagini sono pronte per l’analisi.',
    emailSmsOrAnyMessage: 'E-mail, SMS o qualsiasi messaggio',
    enterUrl: 'Inserisci URL',
    urlPlaceholder: 'https://esempio.com',
    pasteUrlHint: 'Incolla qualsiasi URL da controllare per phishing o malware.',
    camera: 'Fotocamera',
    gallery: 'Galleria',
    designTip: 'Consiglio',
    designTipText: 'Privato – non viene salvato nulla. Verifica sempre direttamente con il marchio.',
    back: 'Indietro',
    backToResult: 'Torna al risultato',
    detailedThreatReport: 'Rapporto dettagliato sulle minacce',
    screenshotAnalysis: 'Analisi screenshot',
    urlAnalysis: 'Analisi URL',
    riskAssessment: 'Valutazione del rischio',
    detectedThreats: 'Minacce rilevate',
    systemFindings: 'Riscontri del sistema',
    extractedScreenshotText: 'Testo estratto dallo screenshot',
    urlInspectionDetails: 'Dettagli dell’ispezione URL',
    aiReview: 'Analisi IA',
    systemReview: 'Analisi del sistema',
    urlNotRecognized: 'Non è stato possibile ottenere un risultato chiaro per questo sito. La nostra IA non riconosce con certezza questo dominio, quindi non è stato valutato completamente. Se non conosci questo sito, trattalo con cautela e verificalo tramite un canale ufficiale.',
    urlNotRecognizedStatus: 'Non valutato',
    aiThreatScore: 'Punteggio di minaccia',
    recommendations: 'Raccomandazioni',
    summary: 'Riepilogo',
    shareReport: 'Condividi rapporto',
    shareFooter: 'Verificato con ScamCheck. Verifica sempre direttamente con la fonte ufficiale.',
    shareError: 'Impossibile aprire il menu di condivisione.',
    hostLabel: 'Host',
    domainNotRecognizedLine: 'Questo dominio non è stato riconosciuto con certezza.',
    impersonatedBrandLabel: 'Possibile marchio contraffatto',
    noImpersonatedBrand: 'Nessun marchio contraffatto rilevato.',
    errorNoApiKey: 'Chiave API non trovata. Aggiungi EXPO_PUBLIC_FOUNDRY_API_KEY al tuo file .env e riavvia l’app.',
    errorApiRequest: 'Impossibile raggiungere il servizio di analisi. Riprova tra un momento.',
    errorImageRead: 'Impossibile leggere l’immagine. Prova a selezionarla di nuovo.',
    reviewScreenshots: 'Rivedi screenshot',
    startNewScan: 'Avvia nuova scansione',
    urlAnalysisPrefix: 'Analisi URL: ',
    deepAnalysisCompleteFor: 'Analisi approfondita completata per',
    securityAnalysisOf: 'Analisi di sicurezza di',
    screenshotLabel: 'screenshot',
    aiThreatScanResult: 'Risultato della scansione delle minacce con IA',
    threatSignals: 'Segnali di minaccia',
    overallRiskScore: 'Punteggio di rischio complessivo',
    analysisConfidence: 'Affidabilità dell’analisi',
    threatLevel: 'Livello di minaccia',
    viewFullReport: 'Vedi rapporto completo',
    dontClickLinks: 'Non cliccare sui link e non scaricare file da questa fonte.',
    reportThis: 'Segnala questo al tuo provider e-mail o al supporto IT.',
    verifySender: 'Verifica l’identità del mittente tramite canali ufficiali.',
    urlInspection: 'Ispezione URL',
    errorTitle: 'Errore',
    invalidUrl: 'Inserisci un URL valido',
    screenshotAnalysisDetected: 'Il contenuto dello screenshot è stato scansionato e sono stati identificati schemi di testo sospetti nelle immagini selezionate.',
    urlAnalysisComplete: 'Analisi URL completata per {url}. Sono stati applicati controlli dettagliati della struttura e regole sulle parole chiave.',
    aiSummaryScreenshot: 'L’analisi IA conferma che lo screenshot contiene schemi di testo tipici del phishing o del furto di credenziali. Il sistema ha rilevato linguaggio di urgenza e richieste di verifica dell’account.',
    aiSummaryUrl: 'Il sistema ha analizzato questo URL alla ricerca di domini falsi (typosquatting), omografi e strutture sospette. Vedi i segnali rilevati qui sotto.',
    aiCommentHigh: 'L’IA suggerisce un’alta probabilità di minaccia e raccomanda un’azione immediata.',
    aiCommentMedium: 'L’IA suggerisce una probabilità di minaccia media. Procedi con cautela.',
    aiCommentLow: 'L’IA suggerisce un rischio da basso a moderato ma raccomanda una verifica.',
    analysisErrorTitle: 'Errore di analisi',
    analysisFailed: 'Analisi non riuscita. Riprova.',
    highRisk: 'Rischio alto',
    mediumRisk: 'Rischio medio',
    lowRisk: 'Rischio basso',
    noTechnicalFlags: 'L’algoritmo non ha trovato segnali tecnici di allarme evidenti.',
  },
  nl: {
    appTitle: 'ScamCheck',
    analyzing: 'Bezig met analyseren...',
    analyzingSubtitle: 'Het bericht wordt gelezen en links worden gecontroleerd. Dit kan een paar seconden duren.',
    positiveFindings: 'Positieve bevindingen',
    noThreatsFound: 'Geen duidelijke dreigingssignalen gedetecteerd.',
    noPositivesFound: 'Geen specifieke geruststellende signalen opgemerkt.',
    recommendation: 'Aanbeveling',
    selectScreenshot: 'Screenshot kiezen',
    analyze: 'Analyseren',
    analyzingPlaceholder: 'Bezig met analyseren...',
    noScreenshot: 'Nog geen screenshot geselecteerd.',
    allowCameraRoll: 'Geef toegang tot je foto’s zodat je een screenshot kunt kiezen.',
    screenshotSelected: 'Screenshot geselecteerd:',
    imagesSelected: 'afbeelding(en) geselecteerd.',
    noImageFound: 'Er kon geen afbeelding uit de kiezer worden geladen.',
    pickerError: 'Er is een fout opgetreden in de afbeeldingskiezer.',
    settings: 'Instellingen',
    settingsSubtitle: 'Kies app-opties en taalvoorkeur.',
    language: 'Taal',
    selected: 'Geselecteerd',
    languageInfoTitle: 'Taalinfo',
    languageInfoDescription: 'Het wijzigen van de taal werkt de beschikbare app-teksten en meldingen bij.',
    homeSubtitle: 'Bescherm je inbox en je vertrouwen door verdachte screenshots te beoordelen voordat je tikt.',
    isThisMessageAScam: 'Is dit bericht oplichting?',
    uploadScreenshotAndGetCheck: 'Upload een screenshot en krijg direct een veiligheidscontrole.',
    enterSuspiciousUrl: 'Voer een verdachte URL in voor dreigingsanalyse.',
    selectAScreenshot: 'Kies een screenshot',
    imagesReadyToAnalyze: 'De afbeeldingen zijn klaar om te analyseren.',
    emailSmsOrAnyMessage: 'E-mail, sms of elk bericht',
    enterUrl: 'URL invoeren',
    urlPlaceholder: 'https://voorbeeld.com',
    pasteUrlHint: 'Plak een URL die je wilt controleren op phishing of malware.',
    camera: 'Camera',
    gallery: 'Galerij',
    designTip: 'Tip',
    designTipText: 'Privé – er wordt niets opgeslagen. Verifieer altijd rechtstreeks bij het merk.',
    back: 'Terug',
    backToResult: 'Terug naar resultaat',
    detailedThreatReport: 'Gedetailleerd dreigingsrapport',
    screenshotAnalysis: 'Screenshot-analyse',
    urlAnalysis: 'URL-analyse',
    riskAssessment: 'Risicobeoordeling',
    detectedThreats: 'Gedetecteerde dreigingen',
    systemFindings: 'Systeembevindingen',
    extractedScreenshotText: 'Geëxtraheerde screenshottekst',
    urlInspectionDetails: 'Details van URL-inspectie',
    aiReview: 'AI-beoordeling',
    systemReview: 'Systeembeoordeling',
    urlNotRecognized: 'We konden geen duidelijk resultaat voor deze site krijgen. Onze AI herkent dit domein niet met zekerheid, dus het is niet volledig beoordeeld. Als je deze site niet kent, wees dan voorzichtig en verifieer via een officieel kanaal.',
    urlNotRecognizedStatus: 'Niet beoordeeld',
    aiThreatScore: 'Dreigingsscore',
    recommendations: 'Aanbevelingen',
    summary: 'Samenvatting',
    shareReport: 'Rapport delen',
    shareFooter: 'Gecontroleerd met ScamCheck. Verifieer altijd rechtstreeks bij de officiële bron.',
    shareError: 'Kan het deelmenu niet openen.',
    hostLabel: 'Host',
    domainNotRecognizedLine: 'Dit domein is niet met zekerheid herkend.',
    impersonatedBrandLabel: 'Mogelijk nagebootst merk',
    noImpersonatedBrand: 'Geen nagebootst merk gedetecteerd.',
    errorNoApiKey: 'API-sleutel niet gevonden. Voeg EXPO_PUBLIC_FOUNDRY_API_KEY toe aan je .env-bestand en start de app opnieuw.',
    errorApiRequest: 'De analyseservice is niet bereikbaar. Probeer het zo opnieuw.',
    errorImageRead: 'Kan de afbeelding niet lezen. Probeer deze opnieuw te selecteren.',
    reviewScreenshots: 'Screenshots bekijken',
    startNewScan: 'Nieuwe scan starten',
    urlAnalysisPrefix: 'URL-analyse: ',
    deepAnalysisCompleteFor: 'Diepgaande analyse voltooid voor',
    securityAnalysisOf: 'Beveiligingsanalyse van',
    screenshotLabel: 'screenshot',
    aiThreatScanResult: 'Resultaat van AI-dreigingsscan',
    threatSignals: 'Dreigingssignalen',
    overallRiskScore: 'Totale risicoscore',
    analysisConfidence: 'Betrouwbaarheid van analyse',
    threatLevel: 'Dreigingsniveau',
    viewFullReport: 'Volledig rapport bekijken',
    dontClickLinks: 'Klik niet op links en download geen bestanden van deze bron.',
    reportThis: 'Meld dit bij je e-mailprovider of IT-ondersteuning.',
    verifySender: 'Verifieer de identiteit van de afzender via officiële kanalen.',
    urlInspection: 'URL-inspectie',
    errorTitle: 'Fout',
    invalidUrl: 'Voer een geldige URL in',
    screenshotAnalysisDetected: 'De screenshotinhoud is gescand en er zijn verdachte tekstpatronen gevonden in de geselecteerde afbeeldingen.',
    urlAnalysisComplete: 'URL-analyse voltooid voor {url}. Gedetailleerde structuurcontroles en trefwoordregels zijn toegepast.',
    aiSummaryScreenshot: 'De AI-beoordeling bevestigt dat de screenshot tekstpatronen bevat die passen bij phishing of diefstal van inloggegevens. Het systeem vond urgente taal en verzoeken om accountverificatie.',
    aiSummaryUrl: 'Het systeem analyseerde deze URL op nepdomeinen (typosquatting), homografen en verdachte structuren. Bekijk de gedetecteerde signalen hieronder.',
    aiCommentHigh: 'De AI suggereert een hoge dreigingskans en raadt onmiddellijke actie aan.',
    aiCommentMedium: 'De AI suggereert een gemiddelde dreigingskans. Ga voorzichtig te werk.',
    aiCommentLow: 'De AI suggereert een laag tot matig risico maar raadt verificatie aan.',
    analysisErrorTitle: 'Analysefout',
    analysisFailed: 'Analyse mislukt. Probeer het opnieuw.',
    highRisk: 'Hoog risico',
    mediumRisk: 'Gemiddeld risico',
    lowRisk: 'Laag risico',
    noTechnicalFlags: 'Het algoritme vond geen duidelijke technische waarschuwingssignalen.',
  },
  pl: {
    appTitle: 'ScamCheck',
    analyzing: 'Analizowanie...',
    analyzingSubtitle: 'Odczytywanie wiadomości i sprawdzanie linków. Może to potrwać kilka sekund.',
    positiveFindings: 'Pozytywne ustalenia',
    noThreatsFound: 'Nie wykryto wyraźnych sygnałów zagrożenia.',
    noPositivesFound: 'Nie odnotowano szczególnych uspokajających sygnałów.',
    recommendation: 'Zalecenie',
    selectScreenshot: 'Wybierz zrzut ekranu',
    analyze: 'Analizuj',
    analyzingPlaceholder: 'Analizowanie...',
    noScreenshot: 'Nie wybrano jeszcze zrzutu ekranu.',
    allowCameraRoll: 'Zezwól na dostęp do zdjęć, aby wybrać zrzut ekranu.',
    screenshotSelected: 'Wybrano zrzut ekranu:',
    imagesSelected: 'wybrano obraz(y).',
    noImageFound: 'Nie udało się załadować obrazu z selektora.',
    pickerError: 'Wystąpił błąd selektora obrazów.',
    settings: 'Ustawienia',
    settingsSubtitle: 'Wybierz opcje aplikacji i język.',
    language: 'Język',
    selected: 'Wybrano',
    languageInfoTitle: 'Informacje o języku',
    languageInfoDescription: 'Zmiana języka zaktualizuje dostępne etykiety i komunikaty aplikacji.',
    homeSubtitle: 'Chroń swoją skrzynkę i zaufanie, oceniając podejrzane zrzuty ekranu przed kliknięciem.',
    isThisMessageAScam: 'Czy ta wiadomość to oszustwo?',
    uploadScreenshotAndGetCheck: 'Prześlij zrzut ekranu i uzyskaj natychmiastowe sprawdzenie bezpieczeństwa.',
    enterSuspiciousUrl: 'Wprowadź podejrzany adres URL do analizy zagrożeń.',
    selectAScreenshot: 'Wybierz zrzut ekranu',
    imagesReadyToAnalyze: 'Obrazy są gotowe do analizy.',
    emailSmsOrAnyMessage: 'E-mail, SMS lub dowolna wiadomość',
    enterUrl: 'Wprowadź URL',
    urlPlaceholder: 'https://przyklad.com',
    pasteUrlHint: 'Wklej dowolny adres URL, który chcesz sprawdzić pod kątem phishingu lub złośliwego oprogramowania.',
    camera: 'Aparat',
    gallery: 'Galeria',
    designTip: 'Wskazówka',
    designTipText: 'Prywatne – nic nie jest zapisywane. Zawsze weryfikuj bezpośrednio u marki.',
    back: 'Wstecz',
    backToResult: 'Powrót do wyniku',
    detailedThreatReport: 'Szczegółowy raport o zagrożeniach',
    screenshotAnalysis: 'Analiza zrzutu ekranu',
    urlAnalysis: 'Analiza URL',
    riskAssessment: 'Ocena ryzyka',
    detectedThreats: 'Wykryte zagrożenia',
    systemFindings: 'Ustalenia systemu',
    extractedScreenshotText: 'Wyodrębniony tekst ze zrzutu',
    urlInspectionDetails: 'Szczegóły inspekcji URL',
    aiReview: 'Analiza SI',
    systemReview: 'Analiza systemu',
    urlNotRecognized: 'Nie udało się uzyskać jednoznacznego wyniku dla tej witryny. Nasza SI nie rozpoznaje tej domeny z pewnością, więc nie została w pełni oceniona. Jeśli nie znasz tej witryny, zachowaj ostrożność i zweryfikuj ją przez oficjalny kanał.',
    urlNotRecognizedStatus: 'Nie oceniono',
    aiThreatScore: 'Wynik zagrożenia',
    recommendations: 'Zalecenia',
    summary: 'Podsumowanie',
    shareReport: 'Udostępnij raport',
    shareFooter: 'Sprawdzono za pomocą ScamCheck. Zawsze weryfikuj bezpośrednio u oficjalnego źródła.',
    shareError: 'Nie można otworzyć menu udostępniania.',
    hostLabel: 'Host',
    domainNotRecognizedLine: 'Ta domena nie została rozpoznana z pewnością.',
    impersonatedBrandLabel: 'Możliwa podrobiona marka',
    noImpersonatedBrand: 'Nie wykryto podrobionej marki.',
    errorNoApiKey: 'Nie znaleziono klucza API. Dodaj EXPO_PUBLIC_FOUNDRY_API_KEY do pliku .env i uruchom ponownie aplikację.',
    errorApiRequest: 'Nie można połączyć się z usługą analizy. Spróbuj ponownie za chwilę.',
    errorImageRead: 'Nie można odczytać obrazu. Spróbuj wybrać go ponownie.',
    reviewScreenshots: 'Przejrzyj zrzuty ekranu',
    startNewScan: 'Rozpocznij nowe skanowanie',
    urlAnalysisPrefix: 'Analiza URL: ',
    deepAnalysisCompleteFor: 'Pogłębiona analiza zakończona dla',
    securityAnalysisOf: 'Analiza bezpieczeństwa dla',
    screenshotLabel: 'zrzut ekranu',
    aiThreatScanResult: 'Wynik skanowania zagrożeń SI',
    threatSignals: 'Sygnały zagrożenia',
    overallRiskScore: 'Ogólny wynik ryzyka',
    analysisConfidence: 'Pewność analizy',
    threatLevel: 'Poziom zagrożenia',
    viewFullReport: 'Zobacz pełny raport',
    dontClickLinks: 'Nie klikaj w linki ani nie pobieraj plików z tego źródła.',
    reportThis: 'Zgłoś to swojemu dostawcy poczty lub wsparciu IT.',
    verifySender: 'Zweryfikuj tożsamość nadawcy przez oficjalne kanały.',
    urlInspection: 'Inspekcja URL',
    errorTitle: 'Błąd',
    invalidUrl: 'Wprowadź prawidłowy adres URL',
    screenshotAnalysisDetected: 'Zawartość zrzutu ekranu została przeskanowana i w wybranych obrazach zidentyfikowano podejrzane wzorce tekstu.',
    urlAnalysisComplete: 'Analiza URL zakończona dla {url}. Zastosowano szczegółowe kontrole struktury i reguły słów kluczowych.',
    aiSummaryScreenshot: 'Analiza SI potwierdza, że zrzut ekranu zawiera wzorce tekstu typowe dla phishingu lub kradzieży danych logowania. System wykrył język pilności i prośby o weryfikację konta.',
    aiSummaryUrl: 'System przeanalizował ten adres URL pod kątem fałszywych domen (typosquatting), homografów i podejrzanej struktury. Zobacz wykryte sygnały poniżej.',
    aiCommentHigh: 'SI sugeruje wysokie prawdopodobieństwo zagrożenia i zaleca natychmiastowe działanie.',
    aiCommentMedium: 'SI sugeruje średnie prawdopodobieństwo zagrożenia. Zachowaj ostrożność.',
    aiCommentLow: 'SI sugeruje niskie lub umiarkowane ryzyko, ale zaleca weryfikację.',
    analysisErrorTitle: 'Błąd analizy',
    analysisFailed: 'Analiza nie powiodła się. Spróbuj ponownie.',
    highRisk: 'Wysokie ryzyko',
    mediumRisk: 'Średnie ryzyko',
    lowRisk: 'Niskie ryzyko',
    noTechnicalFlags: 'Algorytm nie znalazł oczywistych technicznych sygnałów ostrzegawczych.',
  },
  hi: {
    appTitle: 'ScamCheck',
    analyzing: 'विश्लेषण हो रहा है...',
    analyzingSubtitle: 'संदेश पढ़ा जा रहा है और लिंक जाँचे जा रहे हैं। इसमें कुछ सेकंड लग सकते हैं।',
    positiveFindings: 'सकारात्मक निष्कर्ष',
    noThreatsFound: 'कोई स्पष्ट ख़तरे का संकेत नहीं मिला।',
    noPositivesFound: 'कोई विशेष आश्वस्त करने वाला संकेत नहीं देखा गया।',
    recommendation: 'सिफ़ारिश',
    selectScreenshot: 'स्क्रीनशॉट चुनें',
    analyze: 'विश्लेषण करें',
    analyzingPlaceholder: 'विश्लेषण हो रहा है...',
    noScreenshot: 'अभी तक कोई स्क्रीनशॉट नहीं चुना गया।',
    allowCameraRoll: 'स्क्रीनशॉट चुनने के लिए कृपया अपनी तस्वीरों तक पहुँच की अनुमति दें।',
    screenshotSelected: 'स्क्रीनशॉट चुना गया:',
    imagesSelected: 'छवि(याँ) चुनी गईं।',
    noImageFound: 'चयनकर्ता से कोई छवि लोड नहीं हो सकी।',
    pickerError: 'छवि चयनकर्ता में त्रुटि हुई।',
    settings: 'सेटिंग्स',
    settingsSubtitle: 'ऐप विकल्प और भाषा चुनें।',
    language: 'भाषा',
    selected: 'चयनित',
    languageInfoTitle: 'भाषा जानकारी',
    languageInfoDescription: 'भाषा बदलने से ऐप के उपलब्ध लेबल और संदेश अपडेट होंगे।',
    homeSubtitle: 'टैप करने से पहले संदिग्ध स्क्रीनशॉट का मूल्यांकन करके अपने इनबॉक्स और भरोसे की रक्षा करें।',
    isThisMessageAScam: 'क्या यह संदेश धोखाधड़ी है?',
    uploadScreenshotAndGetCheck: 'एक स्क्रीनशॉट अपलोड करें और तुरंत सुरक्षा जाँच पाएँ।',
    enterSuspiciousUrl: 'ख़तरे के विश्लेषण के लिए एक संदिग्ध URL दर्ज करें।',
    selectAScreenshot: 'एक स्क्रीनशॉट चुनें',
    imagesReadyToAnalyze: 'छवियाँ विश्लेषण के लिए तैयार हैं।',
    emailSmsOrAnyMessage: 'ईमेल, SMS या कोई भी संदेश',
    enterUrl: 'URL दर्ज करें',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'फ़िशिंग या मैलवेयर के लिए जाँचने हेतु कोई भी URL पेस्ट करें।',
    camera: 'कैमरा',
    gallery: 'गैलरी',
    designTip: 'सुझाव',
    designTipText: 'निजी — कुछ भी संग्रहीत नहीं होता। हमेशा सीधे ब्रांड से सत्यापित करें।',
    back: 'वापस',
    backToResult: 'परिणाम पर वापस',
    detailedThreatReport: 'विस्तृत ख़तरा रिपोर्ट',
    screenshotAnalysis: 'स्क्रीनशॉट विश्लेषण',
    urlAnalysis: 'URL विश्लेषण',
    riskAssessment: 'जोखिम मूल्यांकन',
    detectedThreats: 'पता लगे ख़तरे',
    systemFindings: 'सिस्टम निष्कर्ष',
    extractedScreenshotText: 'स्क्रीनशॉट से निकाला गया टेक्स्ट',
    urlInspectionDetails: 'URL निरीक्षण विवरण',
    aiReview: 'AI समीक्षा',
    systemReview: 'सिस्टम समीक्षा',
    urlNotRecognized: 'हम इस साइट के लिए स्पष्ट परिणाम नहीं पा सके। हमारा AI इस डोमेन को विश्वास के साथ नहीं पहचानता, इसलिए इसका पूरी तरह मूल्यांकन नहीं हुआ। यदि आप इस साइट को नहीं जानते, तो सावधानी बरतें और किसी आधिकारिक माध्यम से सत्यापित करें।',
    urlNotRecognizedStatus: 'मूल्यांकित नहीं',
    aiThreatScore: 'ख़तरा स्कोर',
    recommendations: 'सिफ़ारिशें',
    summary: 'सारांश',
    shareReport: 'रिपोर्ट साझा करें',
    shareFooter: 'ScamCheck से जाँचा गया। हमेशा सीधे आधिकारिक स्रोत से सत्यापित करें।',
    shareError: 'साझा करने का मेनू नहीं खुल सका।',
    hostLabel: 'होस्ट',
    domainNotRecognizedLine: 'यह डोमेन विश्वास के साथ नहीं पहचाना गया।',
    impersonatedBrandLabel: 'संभावित नक़ली ब्रांड',
    noImpersonatedBrand: 'कोई नक़ली ब्रांड नहीं मिला।',
    errorNoApiKey: 'API कुंजी नहीं मिली। अपनी .env फ़ाइल में EXPO_PUBLIC_FOUNDRY_API_KEY जोड़ें और ऐप पुनः आरंभ करें।',
    errorApiRequest: 'विश्लेषण सेवा तक नहीं पहुँचा जा सका। कृपया थोड़ी देर में पुनः प्रयास करें।',
    errorImageRead: 'छवि नहीं पढ़ी जा सकी। कृपया इसे फिर से चुनने का प्रयास करें।',
    reviewScreenshots: 'स्क्रीनशॉट समीक्षा करें',
    startNewScan: 'नई जाँच शुरू करें',
    urlAnalysisPrefix: 'URL विश्लेषण: ',
    deepAnalysisCompleteFor: 'इसके लिए गहन विश्लेषण पूर्ण',
    securityAnalysisOf: 'इसका सुरक्षा विश्लेषण',
    screenshotLabel: 'स्क्रीनशॉट',
    aiThreatScanResult: 'AI ख़तरा स्कैन परिणाम',
    threatSignals: 'ख़तरे के संकेत',
    overallRiskScore: 'कुल जोखिम स्कोर',
    analysisConfidence: 'विश्लेषण विश्वसनीयता',
    threatLevel: 'ख़तरा स्तर',
    viewFullReport: 'पूरी रिपोर्ट देखें',
    dontClickLinks: 'इस स्रोत से लिंक पर क्लिक न करें या फ़ाइलें डाउनलोड न करें।',
    reportThis: 'इसकी सूचना अपने ईमेल प्रदाता या IT सहायता को दें।',
    verifySender: 'आधिकारिक माध्यमों से भेजने वाले की पहचान सत्यापित करें।',
    urlInspection: 'URL निरीक्षण',
    errorTitle: 'त्रुटि',
    invalidUrl: 'कृपया एक मान्य URL दर्ज करें',
    screenshotAnalysisDetected: 'स्क्रीनशॉट सामग्री को स्कैन किया गया और चुनी गई छवियों में संदिग्ध टेक्स्ट पैटर्न पहचाने गए।',
    urlAnalysisComplete: '{url} के लिए URL विश्लेषण पूर्ण। विस्तृत संरचना जाँच और कीवर्ड नियम लागू किए गए।',
    aiSummaryScreenshot: 'AI समीक्षा पुष्टि करती है कि स्क्रीनशॉट में फ़िशिंग या क्रेडेंशियल चोरी से मेल खाते टेक्स्ट पैटर्न हैं। सिस्टम ने तात्कालिकता वाली भाषा और खाता सत्यापन संकेत पाए।',
    aiSummaryUrl: 'सिस्टम ने इस URL का नक़ली डोमेन (टाइपोस्क्वाटिंग), होमोग्राफ़ और संदिग्ध संरचना के लिए विश्लेषण किया। नीचे पता लगे संकेत देखें।',
    aiCommentHigh: 'AI उच्च ख़तरे की संभावना बताता है और तुरंत कार्रवाई की सिफ़ारिश करता है।',
    aiCommentMedium: 'AI मध्यम ख़तरे की संभावना बताता है। सावधानी से आगे बढ़ें।',
    aiCommentLow: 'AI कम से मध्यम जोखिम बताता है लेकिन सत्यापन की सिफ़ारिश करता है।',
    analysisErrorTitle: 'विश्लेषण त्रुटि',
    analysisFailed: 'विश्लेषण विफल। कृपया पुनः प्रयास करें।',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'कम जोखिम',
    noTechnicalFlags: 'एल्गोरिदम को कोई स्पष्ट तकनीकी चेतावनी संकेत नहीं मिला।',
  },
};

export function t(locale, key) {
  return strings[locale]?.[key] ?? strings.en[key] ?? key;
}

export const defaultLocale = 'en';

// Languages the app supports (must match the keys in `strings`).
export const SUPPORTED_LOCALES = [
  'en', 'tr', 'es', 'de', 'fr', 'ar', 'pt', 'ru', 'it', 'nl', 'pl', 'hi',
];

// Each language shown in its own name, so users recognize their language.
export const LANGUAGE_NAMES = {
  en: 'English',
  tr: 'Türkçe',
  es: 'Español',
  de: 'Deutsch',
  fr: 'Français',
  ar: 'العربية',
  pt: 'Português',
  ru: 'Русский',
  it: 'Italiano',
  nl: 'Nederlands',
  pl: 'Polski',
  hi: 'हिन्दी',
};

// Pick the best starting locale from the device's languages.
// `deviceLocales` is the array from expo-localization's getLocales().
// Falls back to English if the device language is not supported.
export function resolveDeviceLocale(deviceLocales) {
  try {
    if (Array.isArray(deviceLocales)) {
      for (const entry of deviceLocales) {
        // entry.languageCode is a 2-letter code like "en", "tr", "de"
        const code = (entry?.languageCode || '').toLowerCase();
        if (code && SUPPORTED_LOCALES.includes(code)) {
          return code;
        }
      }
    }
  } catch (e) {
    // ignore and fall back
  }
  return defaultLocale;
}
