const strings = {
  en: {
    appTitle: 'ScamCheck',
    analyzing: 'Analyzing...',
    analyzingSubtitle: 'Reading the message and checking links. This can take a few seconds.',
    positiveFindings: 'Positive Findings',
    noThreatsFound: 'No clear threat signals detected.',
    noPositivesFound: 'No specific reassuring signals noted.',
    recommendation: 'Recommendation',
    selectScreenshot: 'Select Screenshot',
    analyze: 'Analyze',
    analyzingPlaceholder: 'Analyzing...',
    noScreenshot: 'No screenshot selected yet.',
    allowCameraRoll: 'Please allow access to your photos so you can select a screenshot.',
    screenshotSelected: 'Screenshot selected:',
    imagesSelected: 'image(s) selected.',
    noImageFound: 'No image could be loaded from the picker result.',
    pickerError: 'Image picker error occurred.',
    settings: 'Settings',
    settingsSubtitle: 'Choose app options and language preference.',
    language: 'Language',
    selected: 'Selected',
    languageInfoTitle: 'Language info',
    languageInfoDescription: 'Switching the language will update available app labels and prompts.',
    homeSubtitle: 'Protect your inbox and brand trust by evaluating suspicious screenshots before you tap.',
    isThisMessageAScam: 'Is this message a scam?',
    uploadScreenshotAndGetCheck: 'Upload a screenshot and get an instant safety check.',
    enterSuspiciousUrl: 'Enter a suspicious URL for threat analysis.',
    selectAScreenshot: 'Select a screenshot',
    imagesReadyToAnalyze: 'Images are ready to analyze.',
    emailSmsOrAnyMessage: 'Email, SMS, or any message',
    enterUrl: 'Enter URL',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'Paste any URL you want to check for phishing or malware threats.',
    camera: 'Camera',
    gallery: 'Gallery',
    designTip: 'Design tip',
    designTipText: 'Private — nothing is stored. Always verify with the brand directly.',
    back: 'Back',
    backToResult: 'Back to Result',
    detailedThreatReport: 'Detailed Threat Report',
    screenshotAnalysis: 'Screenshot Analysis',
    urlAnalysis: 'URL Analysis',
    riskAssessment: 'Risk Assessment',
    detectedThreats: 'Detected Threats',
    systemFindings: 'System findings',
    extractedScreenshotText: 'Extracted screenshot text',
    urlInspectionDetails: 'URL inspection details',
    aiReview: 'AI review',
    aiThreatScore: 'AI Threat Score',
    recommendations: 'Recommendations',
    summary: 'Summary',
    shareReport: 'Share Report',
    exportPdf: 'Export PDF',
    reviewScreenshots: 'Review screenshots',
    startNewScan: 'Start new scan',
    urlAnalysisPrefix: 'URL Analysis: ',
    deepAnalysisCompleteFor: 'Deep analysis complete for',
    securityAnalysisOf: 'Security analysis of',
    screenshotLabel: 'screenshot',
    aiThreatScanResult: 'AI Threat Scan Result',
    threatSignals: 'Threat signals',
    overallRiskScore: 'Overall Risk Score',
    analysisConfidence: 'Analysis Confidence',
    threatLevel: 'Threat Level',
    viewFullReport: 'View Full Report',
    dontClickLinks: 'Do not click on links or download files from this source.',
    reportThis: 'Report this to your email provider or IT support.',
    verifySender: 'Verify sender identity through official channels.',
    urlInspection: 'URL inspection',
    errorTitle: 'Error',
    invalidUrl: 'Please enter a valid URL',
    screenshotAnalysisDetected: 'Screenshot content was scanned and suspicious text patterns were identified in the selected images.',
    urlAnalysisComplete: 'URL analysis complete for {url}. Detailed structure checks and keyword heuristics were applied.',
    aiSummaryScreenshot: 'AI review confirms the screenshot contains text patterns consistent with phishing or credential harvesting. The system found urgent request language and account verification cues.',
    aiSummaryUrl: 'AI review confirms the URL shows suspicious structure and repeated character patterns. It advises treating this site as potentially malicious.',
    aiCommentHigh: 'AI suggests high threat probability and recommends immediate action.',
    aiCommentMedium: 'AI suggests medium threat probability. Proceed with caution.',
    aiCommentLow: 'AI suggests low to moderate risk but recommends verification.',
    analysisErrorTitle: 'Analysis Error',
    analysisFailed: 'Failed to analyze. Please try again.',
  },
  tr: {
    appTitle: 'ScamCheck',
    analyzing: 'Analiz ediliyor...',
    analyzingSubtitle: 'Mesaj okunuyor ve bağlantılar kontrol ediliyor. Birkaç saniye sürebilir.',
    positiveFindings: 'Olumlu Çıkarımlar',
    noThreatsFound: 'Belirgin bir tehdit işareti bulunamadı.',
    noPositivesFound: 'Özel bir güven verici işaret not edilmedi.',
    recommendation: 'Öneri',
    selectScreenshot: 'Ekran Görüntüsü Seç',
    analyze: 'Analiz Et',
    analyzingPlaceholder: 'Analiz ediliyor...',
    noScreenshot: 'Henüz ekran görüntüsü seçilmedi.',
    allowCameraRoll: 'Lütfen fotoğraflarınıza erişime izin verin.',
    screenshotSelected: 'Ekran görüntüsü seçildi:',
    imagesSelected: 'seçilen resim(ler).',
    noImageFound: 'Seçilen resim yüklenemedi.',
    pickerError: 'Resim seçici hatası oluştu.',
    settings: 'Ayarlar',
    settingsSubtitle: 'Uygulama seçeneklerini ve dil tercihlerini seçin.',
    language: 'Dil',
    selected: 'Seçili',
    languageInfoTitle: 'Dil bilgisi',
    languageInfoDescription: 'Dili değiştirmek, kullanılabilir uygulama başlıklarını ve yönergeleri güncelleyecektir.',
    homeSubtitle: 'Şüpheli ekran görüntülerini dokunmadan önce değerlendirerek gelen kutunuzu ve marka güveninizi koruyun.',
    isThisMessageAScam: 'Bu mesaj dolandırıcılık mı?',
    uploadScreenshotAndGetCheck: 'Bir ekran görüntüsü yükleyin ve anında güvenlik kontrolü alın.',
    enterSuspiciousUrl: 'Şüpheli bir URL girin.',
    selectAScreenshot: 'Ekran görüntüsü seçin',
    imagesReadyToAnalyze: 'Resimler analiz için hazır.',
    emailSmsOrAnyMessage: 'E-posta, SMS veya herhangi bir mesaj',
    enterUrl: 'URL girin',
    urlPlaceholder: 'https://example.com',
    pasteUrlHint: 'Kimlik avı veya kötü amaçlı yazılım tehditlerini kontrol etmek için herhangi bir URL yapıştırın.',
    camera: 'Kamera',
    gallery: 'Galeri',
    designTip: 'Tasarım ipucu',
    designTipText: 'Özel — hiçbir şey saklanmaz. Daima markayı resmi kanaldan teyit et.',
    back: 'Geri',
    backToResult: 'Sonuca Geri',
    detailedThreatReport: 'Detaylı Tehdit Raporu',
    screenshotAnalysis: 'Ekran Görüntüsü Analizi',
    urlAnalysis: 'URL Analizi',
    riskAssessment: 'Risk Değerlendirmesi',
    detectedThreats: 'Tespit Edilen Tehditler',
    systemFindings: 'Sistem bulguları',
    extractedScreenshotText: 'Çıkarılan ekran görüntüsü metni',
    urlInspectionDetails: 'URL inceleme ayrıntıları',
    aiReview: 'AI incelemesi',
    aiThreatScore: 'AI Tehdit Puanı',
    recommendations: 'Öneriler',
    summary: 'Özet',
    shareReport: 'Raporu Paylaş',
    exportPdf: 'PDF Dışa Aktar',
    reviewScreenshots: 'Ekran görüntülerini incele',
    startNewScan: 'Yeni tarama başlat',
    urlAnalysisPrefix: 'URL Analizi: ',
    deepAnalysisCompleteFor: 'Derin analiz tamamlandı',
    securityAnalysisOf: 'Güvenlik analizi',
    screenshotLabel: 'ekran görüntüsü',
    aiThreatScanResult: 'AI Tehdit Tarama Sonucu',
    threatSignals: 'Tehdit sinyalleri',
    overallRiskScore: 'Genel Risk Puanı',
    analysisConfidence: 'Analiz Güveni',
    threatLevel: 'Tehdit Seviyesi',
    viewFullReport: 'Tam Raporu Görüntüle',
    dontClickLinks: 'Bu kaynaktan gelen bağlantılara tıklamayın veya dosya indirmeyin.',
    reportThis: 'Bunu e-posta sağlayıcınıza veya BT desteğine bildirin.',
    verifySender: 'Gönderen kimliğini resmi kanallarla doğrulayın.',
    urlInspection: 'URL incelemesi',
    errorTitle: 'Hata',
    invalidUrl: 'Lütfen geçerli bir URL girin.',
    screenshotAnalysisDetected: 'Ekran görüntüsü içeriği tarandı ve seçilen görüntülerde şüpheli metin kalıpları tespit edildi.',
    urlAnalysisComplete: '{url} için URL analizi tamamlandı. Detaylı yapı kontrolleri ve anahtar kelime kuralları uygulandı.',
    aiSummaryScreenshot: 'AI incelemesi, ekran görüntüsünün kimlik avı veya bilgi avı amaçlı metin kalıpları içerdiğini doğruluyor. Sistem acil eylem ve hesap doğrulama ifadeleri buldu.',
    aiSummaryUrl: 'AI incelemesi, URL’nin şüpheli yapı ve tekrarlayan karakter desenleri içerdiğini doğruluyor. Bu site potansiyel olarak kötü amaçlı olarak değerlendiriliyor.',
    aiCommentHigh: 'AI yüksek tehdit olasılığı öneriyor ve derhal işlem yapılmasını tavsiye ediyor.',
    aiCommentMedium: 'AI orta tehdit olasılığı öneriyor. Dikkatli ilerleyin.',
    aiCommentLow: 'AI düşük ila orta risk öneriyor, ancak doğrulama yapılmasını tavsiye ediyor.',
    analysisErrorTitle: 'Analiz Hatası',
    analysisFailed: 'Analiz yapılamadı. Lütfen tekrar deneyin.',
  },
};

export function t(locale, key) {
  return strings[locale]?.[key] ?? strings.en[key] ?? key;
}

export const defaultLocale = 'en';
